name: cortex
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pytorch=2.2.1
  - torchvision=0.17.1
  - numpy=1.26.4
  - matplotlib=3.8.3
  - tqdm=4.66.2
  - ipython=8.21.0
  - pip=24.0
  - pip:
    - black==24.2.0
    - flake8==7.0.0
    - pytest==8.0.2
    - coverage==7.4.3
    - flake8-pyproject==1.2.3